name: Auto build debug apk

on:
  push:
    branches:
      - 'master'
    tags:
      - '*'
jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          cmdline-tools-version: 12266719
      - name: Unit tests
        run: ./gradlew test --stacktrace

  apk:
    name: Generate APK
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          cmdline-tools-version: 12266719
      - name: Build debug APK
        run: ./gradlew --no-daemon build
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: bluetooth-debug
          path: app/build/outputs/apk/debug/app-debug.apk
